### ISSUE TITLE
[FEATURE] Suggestion

### ISSUE THREAD

**Issue by ioannistsil** [NekoHitDev/ritmin-frontend#18]
1. I want to suggest user can type with keyboard deadline date and time
![image](https://user-images.githubusercontent.com/18231967/138409795-86f553af-8875-4f2a-84c9-08350a12e6c7.png)

2. I set 3 milestone on my test project but its only allowed me to have 1 millestone then i press "next button" and finished registation

![image](https://user-images.githubusercontent.com/18231967/138410441-96cc32e6-35e2-46ad-ae6c-5ba797adea0e.png)

3, A more user friendly UI with colors would be appreciated.

4. when i tried to pay for stake , i set sell 100 token , but it ask me 1000 token.

![image](https://user-images.githubusercontent.com/18231967/138410863-f846a134-915a-48bb-95d8-ed4bdb9363f8.png)

this is the suggestion/ bug i found  hope will help you.

**Comment by hurui200320** [comment]
No.2: No idea what's going on, I cannot recreate the issue, might need further investigation.

No.3: The stake/token is set to 10, which means you need to stake 10 tokens for each 1 token you sell. Thus 100 * 10 = 1000. Try a smaller rate next time.

No.1: I'll take a note. Maybe transfer this issue to the frontend repo?

**Comment by ykoitzsch** [comment]
i am closing this issue since the frontend has changed a lot. If the need comes up again to change dates via keyboard we can make a new ticket I guess.
