### ISSUE TITLE
[FEATURE] Cooldown Interval is hard to input.

### ISSUE THREAD

**Issue by leiw5173** [NekoHitDev/ritmin-frontend#19]
**Is your feature request related to a problem? Please describe.**
It is hard to convert the time into milliseconds.

**Describe the solution you'd like**
It should be 'xx year xx day xx hour xx minutes'
![image](https://user-images.githubusercontent.com/73590328/138423865-3a37bfc6-52c3-485b-9a44-fc644bb0406e.png)

**Comment by hurui200320** [comment]
Thanks, I'll transfer the issue to the frontend repo so we can solve this issue when we build the next version.

**Comment by ykoitzsch** [comment]
I am going to close this issue. The input has been changed to hours.

**Comment by ykoitzsch** [comment]
I think smaller cooldown times will rarely make sense, but if the community wishes to have smaller cooldown intervals, it can be looked at again in a different issue.
