### ISSUE TITLE
Tell users that they cannot use the same identifier

### ISSUE THREAD

**Issue by ahfookies** [NekoHitDev/ritmin-frontend#21]
using the same identifier as a currently open project or finished project would result in unknown error 

**Describe the solution you'd like**
describe error and guide users to use other identifier

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/90914218/139567538-f7abe2ba-a9e1-47d3-89ea-19f82d4ae79b.png)

**Comment by hurui200320** [comment]
In the new frontend, using empty/blank identifier will get an error message like this:

![image](https://user-images.githubusercontent.com/8587572/149499485-6cfb8c7c-f0be-4704-b73d-de0dbe6267bb.png)

And will get an error like this if using a duplicated/same identifier:

![image](https://user-images.githubusercontent.com/8587572/149499664-b1a5ceaa-cce8-40f0-9365-637ce415f8e9.png)
